formatter: markdown table
recursive:
  enabled: true
  path: modules
sections:
  hide: []
content: |-
  ## Requirements
  {{ .Requirements }}

  ## Providers
  {{ .Providers }}

  ## Modules
  {{ .Modules }}

  ## Resources
  {{ .Resources }}

  ## Inputs
  {{ .Inputs }}

  ## Outputs
  {{ .Outputs }}
sort:
  enabled: true
  by: required
settings:
  anchor: false
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
